language: java

services:
  - docker

jdk:
  - openjdk8

os:
  - linux

before_script:
  - "sh -e ./ci/scripts/start-services.sh"

script:
  - ./gradlew check

after_failure: cat $PWD/build/reports/tests/*/classes/*.html

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
