language: java

services:
  - redis
  - mysql

jdk:
  - oraclejdk8

os:
  - linux

install: true

before_script:
  - mysql -e 'create database pivotalcla;'
  - mysql -e "create user 'spring' identified by 'password';"
  - mysql -uroot -e "grant all on pivotalcla.* to 'spring'";

script: |
  if [[ "${TRAVIS_PULL_REQUEST}" = "false" && $TRAVIS_BRANCH == 'master' && $TRAVIS_SECURE_ENV_VARS == 'true' ]] ; then
    ./gradlew deploy -Psecurity.oauth2.main.clientId=$CLIENT_ID -Psecurity.oauth2.main.clientSecret=$CLIENT_SECRET -Psecurity.oauth2.pivotal-cla.tokenSecret=$TOKEN_SECRET -PcfUsername=$CF_USERNAME -PcfPassword=$CF_PASSWORD -Pspring.active.profiles.data
  else
    ./gradlew check -Pspring.active.profiles.data
  fi

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
